about=About
Add=Add
adminpassword=Please insert administrator password
alarm0=SCI Failure\n
alarm1=EEPROM Failure\n
alarm10=Over temperature\n
alarm11=Low DC Bus\n
alarm12=Ground I fault\n
alarm13=No Utility\n
alarm14=High DC Bus\n
alarm15=Ref 2.5V Fault\n
alarm16=DC Sensor Fault\n
alarm2=Grid fault\n
alarm3=Impedance fault\n
alarm4=Relay Failure\n
alarm5=Consistent fault\n
alarm6=DC INJ High\n
alarm7=GFCI Failure\n
alarm8=AutoTest failed
alarm9=PV over voltage\n
all=All
browsepvi=Browsing for PVI...
cancel=Cancel
cantcreate=Can't create virtualized PVI, please check virtualization.
changeset=Change settings
CO2=Saved CO2
commtype=Communication type
commtype1=Serial direct
commtype2=Network Netman
commtype3=Serial EZ Logger
commtype4=Network EZ Logger
counters=Counters
currency=Currency
Currenttogrid=Current:
current=Current
customer=Customer
days=Days
default=Default
detail=Detail
email=Email
email1=Email 1
email2=Email 2
email3=Email 3
emailaddr1=Email address 1
emailaddr2=Email address 2
emailaddr3=Email address 3
emaillogic=Email logic
enabledata=Enable data log
enableemail=Enable Email
enablehttp=Enable HTTP
enablesms=Enable SMS
error=Error
etot=Total Energy
etotbar=Daily Energy
etotbar2=Monthly Energy
euro=\u20AC
export=Export...
fault=Fault
feeding=Feeding configuration
frequency=Frequency
from=From
fwver=FW Version
general=General
GridFrequency=Grid frequency:
Gridimpedance=Impedance:
Gridvoltage=Voltage:
grid=Grid (AC)
gsmport=GSM port
hours=Hours
htot=Total Hours
impedance=Impedance
insertip=Insert IP address
internal=Internal data log
inverter=Inverter
ipaddress=IP Address
load=Load files
loadprm=Load parameters
log&tools=Log & Tools
log=Log
logconfig=Log config
loglento=Slow sampling log
logveloce=Fast sampling log
model=Model
modifyvirtual=Modify virtualization scheme
na=N/A
name=Name
netman=NetMan
ok=Ok
permfault=Permanent fault
ph1=Phone 1
ph2=Phone 2
ph3=Phone 3
PhaseR=Phase R
PhaseS=Phase S
PhaseT=Phase T
phone1=Phone number 1
phone2=Phone number 2
phone3=Phone number 3
photoinverter=PV modules (DC)
port=Port
Powertogrid=Power:
power=Nominal power
powerac=Power
powerdc=Power DC
powertogrid=Power to grid
PV1Curr=MPPT1 current:
PV1Volt=MPPT1 voltage:
PV2Curr=MPPT2 current:
PV2Volt=MPPT2 voltage:
PV3Curr=MPPT3 current:
PV3Volt=MPPT3 voltage:
pvdevices=PV Devices
PVIData=PVI Data
pviname=Please insert PVI name
quit=Quit
quitsure=Do you want to quit without saving?
realtime=Real time update
Remove=Remove
remuneration=Remuneration/kWh
resetcount=Reset Counters
revenue=Revenue
ritann=Yearly history sampling interval (hour)
ritgio=Fast sampling log interval (sec)
ritmen=Monthly history sampling interval (hour)
ritset=Slow sampling log interval (min)
runservice=Run as a background service
saveexit=Save and exit
selectpvi=Please select a PVI from the list
selectstandard=Select a standard
semlog=Smart Energy Manager data log
senderaddr=Sender address
serialport=Serial Port
services=Services
setting1=PV start-up voltage
setting2=Time to connect grid
setting3=Minimum operational grid voltage
setting4=Maximum operational grid voltage
setting5=Minimum operational grid frequency
setting6=Maximum operational grid frequency
setting7=Maximum operational grid impedance
setting8=Allowable Zac variation
setup=Setup
sms=SMS
smscenter=SMS center
smsinit=SMS init
smslogic=SMS logic
smssend=SMS send
smtpserv=SMTP server
stop=Stop
string30long=The string on SMS configuration must be maximum 30 character long.
string50long=The string on Email config must be maximum 50 character long.
sun=Sun
temperature=Temperature
thismonth=This month
thisweek=This week
thisyear=This year
to=to
today=Today
tools=Tools
virtualize1=Virtualize 1-Phase PVI
virtualize2=Virtualize 2-Phases PVI
virtualize3=Virtualize 3-Phases PVI
voltage=Voltage
wait=Wait
weather=Weather forecast
wrongpwd=Wrong password
